package dotenv

import (
	"bytes"
	"errors"
	"strings"
	"testing"
)

// failAfter fails every write after n successful ones.
type failAfter struct{ n int }

func (f *failAfter) Write(p []byte) (int, error) {
	if f.n <= 0 {
		return 0, errors.New("disk full")
	}
	f.n--
	return len(p), nil
}

func TestTabEscape(t *testing.T) {
	got, err := Parse(strings.NewReader(`A="x\ty"`))
	if err != nil || got[0].Value != "x\ty" {
		t.Fatalf("%v %v", got, err)
	}
}

func TestWritersPropagateErrors(t *testing.T) {
	keys := []ExampleKey{{Key: "A", Kind: "secret"}}
	for name, fn := range map[string]func(w *failAfter) error{
		"Write":            func(w *failAfter) error { return Write(w, []Entry{{"A", "1"}}) },
		"WriteExample hdr": func(w *failAfter) error { return WriteExample(w, "h", keys) },
		"WriteKeys hdr":    func(w *failAfter) error { return WriteKeys(w, "h", keys) },
		"AppendKeys hdr":   func(w *failAfter) error { return AppendKeys(w, keys) },
	} {
		if err := fn(&failAfter{0}); err == nil {
			t.Errorf("%s: want error", name)
		}
	}
	// header succeeds, key line fails
	if err := WriteKeys(&failAfter{1}, "h", keys); err == nil {
		t.Error("key line: want error")
	}
}

func TestWriteKeysAndAppendKeys(t *testing.T) {
	var b bytes.Buffer
	WriteKeys(&b, "head", []ExampleKey{{Key: "A", Kind: "secret", Sources: []string{"x.yml"}}})
	AppendKeys(&b, []ExampleKey{{Key: "B", Kind: "variable"}})
	want := "# head\n# Generated by env4ci gen. Fill in values; this file must not be committed.\n\n# secret · x.yml\nA=\n\n# --- added by env4ci gen ---\n\n# variable\nB=\n"
	if b.String() != want {
		t.Fatalf("got %q", b.String())
	}
}

func TestMultiLineQuoted(t *testing.T) {
	in := "KEY=\"-----BEGIN OPENSSH PRIVATE KEY-----\nabc\\\"def\n-----END OPENSSH PRIVATE KEY-----\"\nNEXT=1\nRAW='a\nb'\nESC=\"x\\\"\"\n"
	got, err := Parse(strings.NewReader(in))
	if err != nil {
		t.Fatal(err)
	}
	want := []Entry{
		{"KEY", "-----BEGIN OPENSSH PRIVATE KEY-----\nabc\"def\n-----END OPENSSH PRIVATE KEY-----"},
		{"NEXT", "1"}, {"RAW", "a\nb"}, {"ESC", "x\""},
	}
	if len(got) != len(want) {
		t.Fatalf("got %#v", got)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("%d: got %#v want %#v", i, got[i], want[i])
		}
	}
	if _, err := Parse(strings.NewReader("A=\"never closed\nB=2\n")); err == nil || !strings.Contains(err.Error(), "line 1: unterminated") {
		t.Fatalf("err = %v", err)
	}
	if _, err := Parse(strings.NewReader("A='never\n")); err == nil {
		t.Fatal("want error")
	}
}
