// Package dotenv parses and writes .env files.
package dotenv

import (
	"bufio"
	"fmt"
	"io"
	"sort"
	"strings"
)

// Entry is one KEY=VALUE pair in file order.
type Entry struct {
	Key   string
	Value string
}

// Parse reads KEY=VALUE lines. Supports comments, blank lines, an optional
// "export " prefix, and single/double quoted values (\n, \", \\ escapes in
// double quotes). A quoted value may span lines (pasted PEM keys).
func Parse(r io.Reader) ([]Entry, error) {
	var out []Entry
	seen := map[string]int{}
	sc := bufio.NewScanner(r)
	sc.Buffer(make([]byte, 64*1024), 1024*1024)
	line := 0
	for sc.Scan() {
		line++
		s := strings.TrimSpace(sc.Text())
		if s == "" || strings.HasPrefix(s, "#") {
			continue
		}
		s = strings.TrimPrefix(s, "export ")
		eq := strings.IndexByte(s, '=')
		if eq <= 0 {
			return nil, fmt.Errorf("line %d: expected KEY=VALUE", line)
		}
		key := strings.TrimSpace(s[:eq])
		raw := strings.TrimSpace(s[eq+1:])
		start := line
		// An opening quote without its closing quote continues on next lines.
		for raw != "" && (raw[0] == '"' || raw[0] == '\'') && unterminated(raw) {
			if !sc.Scan() {
				return nil, fmt.Errorf("line %d: unterminated quoted value", start)
			}
			line++
			raw += "\n" + strings.TrimRight(sc.Text(), "\r")
		}
		val := parseValue(raw)
		if i, dup := seen[key]; dup {
			out[i].Value = val // last one wins, like most dotenv loaders
			continue
		}
		seen[key] = len(out)
		out = append(out, Entry{Key: key, Value: val})
	}
	return out, sc.Err()
}

// unterminated reports whether a value opening with a quote lacks its
// closing quote (escaped \" does not close a double-quoted value).
func unterminated(v string) bool {
	q := v[0]
	for i := 1; i < len(v); i++ {
		if q == '"' && v[i] == '\\' {
			i++
			continue
		}
		if v[i] == q {
			return false
		}
	}
	return true
}

// parseValue decodes one value; Parse has already joined lines so quoted
// values are terminated.
func parseValue(v string) string {
	if v == "" {
		return ""
	}
	switch v[0] {
	case '\'':
		end := strings.IndexByte(v[1:], '\'')
		return v[1 : end+1]
	case '"':
		var b strings.Builder
		for i := 1; i < len(v); i++ {
			c := v[i]
			if c == '"' {
				break
			}
			if c == '\\' && i+1 < len(v) {
				i++
				switch v[i] {
				case 'n':
					b.WriteByte('\n')
				case 't':
					b.WriteByte('\t')
				default:
					b.WriteByte(v[i])
				}
				continue
			}
			b.WriteByte(c)
		}
		return b.String()
	}
	if i := strings.Index(v, " #"); i >= 0 {
		v = strings.TrimSpace(v[:i])
	}
	return v
}

// Write emits entries sorted by key, double-quoting every value.
func Write(w io.Writer, entries []Entry) error {
	sorted := append([]Entry(nil), entries...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Key < sorted[j].Key })
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`, "\t", `\t`)
	for _, e := range sorted {
		if _, err := fmt.Fprintf(w, "%s=\"%s\"\n", e.Key, r.Replace(e.Value)); err != nil {
			return err
		}
	}
	return nil
}

// ExampleKey is one key for a generated .env.example.
type ExampleKey struct {
	Key      string
	Kind     string
	Stages   []string
	Branches []string // omitted from the comment when it runs on every branch
	Sources  []string
	// Group keeps related keys together: a blank line separates groups,
	// keys of one group follow each other. Empty = every key on its own.
	Group string
}

// WriteExample emits KEY= lines with a comment saying where each key is used.
func WriteExample(w io.Writer, header string, keys []ExampleKey) error {
	if _, err := fmt.Fprintf(w, "# %s\n# Generated by env4ci scan. Fill in values; do not commit the filled file.\n", header); err != nil {
		return err
	}
	return writeKeyLines(w, keys)
}

// WriteKeys writes a fresh file: header comment, then commented KEY= lines.
func WriteKeys(w io.Writer, header string, keys []ExampleKey) error {
	if _, err := fmt.Fprintf(w, "# %s\n# Generated by env4ci gen. Fill in values; this file must not be committed.\n", header); err != nil {
		return err
	}
	return writeKeyLines(w, keys)
}

// AppendKeys appends commented KEY= lines under a marker.
func AppendKeys(w io.Writer, keys []ExampleKey) error {
	if _, err := io.WriteString(w, "\n# --- added by env4ci gen ---\n"); err != nil {
		return err
	}
	return writeKeyLines(w, keys)
}

func writeKeyLines(w io.Writer, keys []ExampleKey) error {
	for i, k := range keys {
		comment := k.Kind
		if len(k.Stages) > 0 {
			comment += " · stages: " + strings.Join(k.Stages, ", ")
		}
		if len(k.Branches) > 1 || (len(k.Branches) == 1 && k.Branches[0] != "*") {
			comment += " · branches: " + strings.Join(k.Branches, ", ")
		}
		if len(k.Sources) > 0 {
			comment += " · " + strings.Join(k.Sources, ", ")
		}
		sep := "\n"
		if i > 0 && k.Group != "" && k.Group == keys[i-1].Group {
			sep = ""
		}
		if _, err := fmt.Fprintf(w, "%s# %s\n%s=\n", sep, comment, k.Key); err != nil {
			return err
		}
	}
	return nil
}

// Set replaces key's value in a .env file's content, keeping every other
// line (comments, order, other quoting) as it was. The last definition of
// key is replaced, matching Parse; a missing key is appended.
func Set(content, key, value string) string {
	lines := strings.SplitAfter(content, "\n")
	if lines[len(lines)-1] == "" {
		lines = lines[:len(lines)-1]
	}
	start, end, export := -1, -1, false
	for i := 0; i < len(lines); i++ {
		s := strings.TrimSpace(lines[i])
		if s == "" || strings.HasPrefix(s, "#") {
			continue
		}
		exp := strings.HasPrefix(s, "export ")
		s = strings.TrimPrefix(s, "export ")
		eq := strings.IndexByte(s, '=')
		if eq <= 0 {
			continue
		}
		first := i
		raw := strings.TrimSpace(s[eq+1:])
		for raw != "" && (raw[0] == '"' || raw[0] == '\'') && unterminated(raw) && i+1 < len(lines) {
			i++
			raw += "\n" + strings.TrimRight(lines[i], "\r\n")
		}
		if strings.TrimSpace(s[:eq]) == key {
			start, end, export = first, i, exp
		}
	}
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "\n", `\n`, "\t", `\t`)
	line := fmt.Sprintf("%s=\"%s\"\n", key, r.Replace(value))
	if export {
		line = "export " + line
	}
	if start < 0 {
		if content != "" && !strings.HasSuffix(content, "\n") {
			content += "\n"
		}
		return content + line
	}
	if !strings.HasSuffix(lines[end], "\n") {
		line = strings.TrimSuffix(line, "\n")
	}
	return strings.Join(lines[:start], "") + line + strings.Join(lines[end+1:], "")
}
