package main

import (
	"bufio"
	"bytes"
	"errors"
	"fmt"
	"io"
	"os"
	"path"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/bakhod1r/env4ci/internal/infrastructure/config"
)

// initPlan is everything "env4ci init" writes into env4ci.yaml.
type initPlan struct {
	Targets      []string // github, gitlab, vault
	Environments []string // one or many
	Repo         string   // owner/name or group/project
	VaultAddr    string
	VaultMount   string
	VaultPath    string
}

// branchFor guesses the branch that deploys to env.
func branchFor(env string) string {
	switch env {
	case "production", "prod":
		return "main"
	case "staging", "stage":
		return "develop"
	}
	return env
}

// SecretsDir holds every generated file; it is gitignored as a whole.
const SecretsDir = ".env4ci"

func envFileFor(env string) string { return SecretsDir + "/" + env + ".env" }

var initTmpl = template.Must(template.New("init").Funcs(template.FuncMap{
	"branch": branchFor, "file": envFileFor, "authFile": func() string { return SecretsDir + "/env4ci.env" }, "q": func(s string) string { return fmt.Sprintf("%q", s) },
	"has": func(xs []string, x string) bool {
		for _, v := range xs {
			if v == x {
				return true
			}
		}
		return false
	},
}).Parse(`# env4ci configuration (generated by "env4ci init").
# Tokens come from GITHUB_TOKEN / GITLAB_TOKEN / VAULT_TOKEN, never this file.

# Unmatched keys default to secret (safe). First matching rule wins.
default: secret
rules:
  - { pattern: "*SECRET*",   type: secret }
  - { pattern: "*PASSWORD*", type: secret }
  - { pattern: "*TOKEN*",    type: secret }
  - { pattern: "*KEY*",      type: secret }
  - { pattern: "APP_*",      type: variable }
  - { pattern: "LOG_*",      type: variable }

# Branch -> environment. "env4ci push" on a branch writes to its environment.
branches:
{{- range .Environments}}
  {{branch . | q}}: {{.}}
{{- end}}

# env4ci's own tokens/addresses (generated, gitignored with the folder).
auth_file: {{authFile}}

# Environment -> local file. Everything in .env4ci/ is gitignored.
environments:
{{- range .Environments}}
  {{.}}: {{file .}}
{{- end}}

targets:
{{- if has .Targets "github"}}
  github:
    repo: {{if .Repo}}{{.Repo}}{{else}}owner/name{{end}}
{{- end}}
{{- if has .Targets "gitlab"}}
  gitlab:
    project: {{if .Repo}}{{.Repo}}{{else}}group/project{{end}}
    protected: true
{{- end}}
{{- if has .Targets "vault"}}
  vault:
    address: {{if .VaultAddr}}{{.VaultAddr}}{{else}}https://vault.example.com:8200{{end}}
    mount: {{.VaultMount}}
    path: {{.VaultPath}}   # {env} = environment name
{{- end}}
`))

func renderInit(p initPlan) ([]byte, error) {
	if len(p.Targets) == 0 {
		return nil, errors.New("init: at least one target (github, gitlab, vault)")
	}
	if len(p.Environments) == 0 {
		return nil, errors.New("init: at least one environment")
	}
	for _, t := range p.Targets {
		if t != "github" && t != "gitlab" && t != "vault" {
			return nil, fmt.Errorf("init: unknown target %q (want github, gitlab, vault)", t)
		}
	}
	for _, e := range p.Environments {
		if !keyLike(e) {
			return nil, fmt.Errorf("init: environment %q: use letters, digits, - or _", e)
		}
	}
	seen := map[string]string{}
	for _, e := range p.Environments {
		b := branchFor(e)
		if prev, dup := seen[b]; dup {
			return nil, fmt.Errorf("init: environments %q and %q both map to branch %q; edit branches: after init", prev, e, b)
		}
		seen[b] = e
	}
	var buf bytes.Buffer
	if err := initTmpl.Execute(&buf, p); err != nil {
		return nil, err
	}
	// The output must load with the real config parser.
	tmp, err := os.CreateTemp("", "env4ci-init-*.yaml")
	if err != nil {
		return nil, err
	}
	defer func() { _ = os.Remove(tmp.Name()) }()
	_, _ = tmp.Write(buf.Bytes())
	_ = tmp.Close()
	if _, err := config.Load(tmp.Name()); err != nil {
		return nil, fmt.Errorf("init: generated config is invalid: %w", err)
	}
	return buf.Bytes(), nil
}

func keyLike(s string) bool {
	if s == "" {
		return false
	}
	for _, r := range s {
		ok := r == '-' || r == '_' || r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9'
		if !ok {
			return false
		}
	}
	return true
}

func splitList(s string) []string {
	var out []string
	for _, p := range strings.FieldsFunc(s, func(r rune) bool { return r == ',' || r == ' ' }) {
		out = append(out, strings.ToLower(strings.TrimSpace(p)))
	}
	return out
}

// defaultsFromGit pre-fills targets and repo from the remote.
func defaultsFromGit(git gitReader) initPlan {
	p := initPlan{Targets: []string{"github"}, Environments: []string{"production"}, VaultMount: "secret"}
	if r, err := git.Remote(); err == nil {
		p.Repo = r.Path
		if r.Provider != "" {
			p.Targets = []string{r.Provider}
		}
	}
	p.VaultAddr = os.Getenv("VAULT_ADDR")
	name := "app"
	if p.Repo != "" {
		name = path.Base(p.Repo)
	}
	p.VaultPath = name + "/{env}"
	return p
}

// askInit prompts on in/out; empty answers keep defaults.
func askInit(in io.Reader, out io.Writer, d initPlan) initPlan {
	r := bufio.NewReader(in)
	ask := func(q, def string) string {
		fmt.Fprintf(out, "%s [%s]: ", q, def)
		line, _ := r.ReadString('\n')
		if line = strings.TrimSpace(line); line != "" {
			return line
		}
		return def
	}
	d.Targets = splitList(ask("Targets (github, gitlab, vault; comma-separated)", strings.Join(d.Targets, ",")))
	d.Environments = splitList(ask("Environments (one or many, comma-separated)", strings.Join(d.Environments, ",")))
	if contains(d.Targets, "github") || contains(d.Targets, "gitlab") {
		d.Repo = ask("Repository (owner/name or group/project)", first(d.Repo, "owner/name"))
	}
	if contains(d.Targets, "vault") {
		d.VaultAddr = ask("Vault address", first(d.VaultAddr, "https://vault.example.com:8200"))
		d.VaultMount = ask("Vault KV v2 mount", d.VaultMount)
		d.VaultPath = ask("Vault path ({env} = environment)", d.VaultPath)
	}
	return d
}

func contains(xs []string, x string) bool {
	for _, v := range xs {
		if v == x {
			return true
		}
	}
	return false
}

func isTerminal(r io.Reader) bool {
	f, ok := r.(*os.File)
	if !ok {
		return false
	}
	st, err := f.Stat()
	return err == nil && st.Mode()&os.ModeCharDevice != 0
}

// cmdInitWizard writes env4ci.yaml (refuses to overwrite), creates an empty
// .env file per environment if missing, and gitignores them.
func cmdInitWizard(o opts, in io.Reader, out io.Writer, git gitReader, interactive bool) error {
	p := defaultsFromGit(git)
	switch {
	case o.targets != "" || o.envs != "":
		if o.targets != "" {
			p.Targets = splitList(o.targets)
		}
		if o.envs != "" {
			p.Environments = splitList(o.envs)
		}
		if o.repo != "" {
			p.Repo = o.repo
		}
	case interactive:
		p = askInit(in, out, p)
	}
	b, err := renderInit(p)
	if err != nil {
		return err
	}
	f, err := os.OpenFile(o.config, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
	if err != nil {
		return err
	}
	if _, err := f.Write(b); err != nil {
		f.Close()
		return err
	}
	if err := f.Close(); err != nil {
		return err
	}
	ui := newPalette(out)
	fmt.Fprintf(out, "%s wrote %s (targets: %s; environments: %s)\n", ui.Green("✓"), o.config, strings.Join(p.Targets, ", "), strings.Join(p.Environments, ", "))

	cfg, err := config.Load(o.config)
	if err != nil {
		return err
	}
	if err := cmdGen(cfg, o, out); err != nil {
		return err
	}
	if err := writeMakefile(filepath.Join(filepath.Dir(o.config), "Makefile"), out); err != nil {
		return err
	}
	fmt.Fprintln(out, ui.Dim("next: put tokens in "+cfg.AuthPath()+", fill the environment files, then run \"env4ci diff\""))
	return nil
}
