package main

import (
	"errors"
	"fmt"
	"io"
	"os"
	"strings"
)

const (
	makeBegin = "# >>> env4ci"
	makeEnd   = "# <<< env4ci"
)

// makeBlock is the Makefile section env4ci owns. ENV picks an environment
// (default: current branch via branches:), TARGET a provider (github,
// gitlab, vault; default: the only configured one).
const makeBlock = makeBegin + ` (generated by "env4ci makefile"; rerun it to refresh, edits inside are replaced)
ENV4CI ?= env4ci
ENV    ?=
TARGET ?=
ENV4CI_FLAGS = $(if $(ENV),-e $(ENV))

.PHONY: env-gen env-scan env-verify env-diff env-diff-all env-push env-push-all env-pull env-drift env-check env-leaks

env-gen: ## create/complete .env4ci/ files from env4ci.yaml
	$(ENV4CI) gen

env-scan: ## list variables the CI files use
	$(ENV4CI) scan

env-verify: ## log in with SSH keys / registry tokens from the env file
	$(ENV4CI) verify $(ENV4CI_FLAGS)

env-diff: ## show what push would change (ENV=, TARGET=)
	$(ENV4CI) diff $(TARGET) $(ENV4CI_FLAGS)

env-diff-all: ## diff every environment
	$(ENV4CI) diff $(TARGET) --all

env-push: ## verify, confirm, write (ENV=, TARGET=)
	$(ENV4CI) push $(TARGET) $(ENV4CI_FLAGS)

env-push-all: ## push every environment
	$(ENV4CI) push $(TARGET) --all

env-pull: ## write remote values to a local file (ENV=, TARGET=)
	$(ENV4CI) pull $(TARGET) $(ENV4CI_FLAGS)

env-drift: ## exit 2 if any environment differs from its env file (CI check)
	$(ENV4CI) diff $(TARGET) --all --exit-code

env-check: ## exit 2 if CI files use keys the provider lacks (CI check)
	$(ENV4CI) check $(TARGET) $(if $(ENV),-e $(ENV),--all)

env-leaks: ## exit 2 if tracked files contain secret values from local env files
	$(ENV4CI) leaks
` + makeEnd + "\n"

// writeMakefile adds or refreshes the env4ci block, leaving the rest of the
// Makefile untouched.
func writeMakefile(path string, out io.Writer) error {
	old, err := os.ReadFile(path)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	s := string(old)
	action := "added env4ci targets to"
	switch begin, end := strings.Index(s, makeBegin), strings.Index(s, makeEnd); {
	case begin >= 0 && end > begin:
		rest := s[end+len(makeEnd):]
		rest = strings.TrimPrefix(rest, "\n")
		s = s[:begin] + makeBlock + rest
		action = "refreshed env4ci targets in"
	case begin >= 0 || end >= 0:
		return fmt.Errorf("%s: unbalanced env4ci markers; fix or remove %q / %q", path, makeBegin, makeEnd)
	case s == "":
		s = makeBlock
		action = "created"
	default:
		if !strings.HasSuffix(s, "\n") {
			s += "\n"
		}
		s += "\n" + makeBlock
	}
	if s == string(old) {
		fmt.Fprintf(out, "%s %s is up to date\n", newPalette(out).Dim("="), path)
		return nil
	}
	if err := os.WriteFile(path, []byte(s), 0o644); err != nil { // #nosec G306 G703 -- path is <config dir>/Makefile; committed, not secret
		return err
	}
	fmt.Fprintf(out, "%s %s %s (make env-diff, env-push, env-verify ...)\n", newPalette(out).Green("✓"), action, path)
	return nil
}
